# Generated by Django 5.2.9 on 2026-01-12 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название исполнителя')),
                ('color', models.CharField(max_length=30, verbose_name='Цвет исполнителя в таблице')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(default='#3498db', max_length=30, verbose_name='Цвет операции в таблице')),
                ('duration', models.IntegerField(default=10, verbose_name='Длительность операции (в секундах)')),
                ('start_time', models.IntegerField(blank=True, null=True, verbose_name='Секунда старта')),
                ('finish_time', models.IntegerField(blank=True, null=True, verbose_name='Секунда финиша')),
                ('dependencies', models.ManyToManyField(blank=True, related_name='dependent_tasks', to='cicklogramus.task')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='cicklogramus.project')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='cicklogramus.worker', verbose_name='Исполнитель')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
