# Generated by Django 4.2.3 on 2026-07-23 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cicklogramus", "0003_alter_task_options_operationblock_operationblockitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationblock",
            name="worker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operation_blocks",
                to="cicklogramus.worker",
            ),
        ),
    ]
